### ISSUE TITLE
Could you please license this WordPress compaible?

### ISSUE THREAD

**Issue by nextgenthemes** [tombryan/social-icon-font#1]
Please license this in [one of this font licenses](http://codex.wordpress.org/Theme_Review#GPL-Compatible_Font_Licenses), i would say SIL Open Font License (OFL) is a good fit, most open webfonts use it AFAK.

If you don't like licenses please consider [unlicense.org](http://unlicense.org/)

**Comment by tombryan** [comment]
Hi @nextgenthemes - great idea, thank you. I've added the licence :)
